/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package launchpad;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author Parichhit
 */

        
        
public class MainFrame extends javax.swing.JFrame {

    private int count=1;

   
   

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(238, 248, 251));
        jPanel1.setFocusable(false);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Desktop\\LaunchPad\\Alphabets\\Q.png")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton1.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setToolTipText("");
        jButton2.setFocusable(false);
        jButton2.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton2.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setFocusable(false);
        jButton3.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton3.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFocusable(false);
        jButton4.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton4.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFocusable(false);
        jButton5.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton5.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFocusable(false);
        jButton6.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton6.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton6.setOpaque(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFocusable(false);
        jButton7.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton7.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFocusable(false);
        jButton8.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton8.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFocusable(false);
        jButton9.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton9.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(204, 204, 204));
        jButton10.setFocusable(false);
        jButton10.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton10.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton10.setOpaque(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(204, 204, 204));
        jButton11.setFocusable(false);
        jButton11.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton11.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton11.setOpaque(false);
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(204, 204, 204));
        jButton12.setFocusable(false);
        jButton12.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton12.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton12.setOpaque(false);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFocusable(false);
        jButton13.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton13.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton13.setOpaque(false);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(204, 204, 204));
        jButton14.setFocusable(false);
        jButton14.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton14.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton14.setOpaque(false);
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(204, 204, 204));
        jButton15.setFocusable(false);
        jButton15.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton15.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton15.setOpaque(false);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(204, 204, 204));
        jButton16.setFocusable(false);
        jButton16.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton16.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton16.setOpaque(false);
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setFocusable(false);
        jButton17.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton17.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton17.setOpaque(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFocusable(false);
        jButton18.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton18.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton18.setOpaque(false);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setFocusable(false);
        jButton19.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton19.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton19.setOpaque(false);
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setBackground(new java.awt.Color(204, 204, 204));
        jButton20.setFocusable(false);
        jButton20.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton20.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton20.setOpaque(false);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(204, 204, 204));
        jButton21.setFocusable(false);
        jButton21.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton21.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton21.setOpaque(false);
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(204, 204, 204));
        jButton22.setFocusable(false);
        jButton22.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton22.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton22.setOpaque(false);
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(204, 204, 204));
        jButton23.setFocusable(false);
        jButton23.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton23.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton23.setOpaque(false);
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(204, 204, 204));
        jButton24.setFocusable(false);
        jButton24.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton24.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton24.setOpaque(false);
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(204, 204, 204));
        jButton25.setFocusable(false);
        jButton25.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton25.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton25.setOpaque(false);
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(204, 204, 204));
        jButton26.setFocusable(false);
        jButton26.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton26.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton26.setOpaque(false);
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jButton27.setBackground(new java.awt.Color(204, 204, 204));
        jButton27.setFocusable(false);
        jButton27.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton27.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton27.setOpaque(false);
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });

        jButton28.setBackground(new java.awt.Color(204, 204, 204));
        jButton28.setFocusable(false);
        jButton28.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton28.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton28.setOpaque(false);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });

        jButton29.setBackground(new java.awt.Color(204, 204, 204));
        jButton29.setFocusable(false);
        jButton29.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton29.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton29.setOpaque(false);
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });

        jButton30.setBackground(new java.awt.Color(204, 204, 204));
        jButton30.setFocusable(false);
        jButton30.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton30.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton30.setOpaque(false);
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });

        jButton31.setBackground(new java.awt.Color(204, 204, 204));
        jButton31.setFocusable(false);
        jButton31.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton31.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton31.setOpaque(false);
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });

        jButton32.setBackground(new java.awt.Color(204, 204, 204));
        jButton32.setFocusable(false);
        jButton32.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton32.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton32.setOpaque(false);
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });

        jButton33.setBackground(new java.awt.Color(204, 204, 204));
        jButton33.setFocusable(false);
        jButton33.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton33.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton33.setOpaque(false);
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });

        jButton34.setBackground(new java.awt.Color(204, 204, 204));
        jButton34.setFocusable(false);
        jButton34.setMaximumSize(new java.awt.Dimension(1000, 75));
        jButton34.setMinimumSize(new java.awt.Dimension(1000, 75));
        jButton34.setOpaque(false);
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KeyBeats");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == KeyEvent.VK_Q) {
               jButton1.doClick();
            }
        
        if (evt.getKeyCode() == KeyEvent.VK_W) {
               jButton2.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_E) {
            jButton3.doClick();                
            }
        if (evt.getKeyCode() == KeyEvent.VK_R) {
            jButton4.doClick();   
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_T) {
            jButton5.doClick();   
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_Y) {
            jButton6.doClick(); 
            }
        if (evt.getKeyCode() == KeyEvent.VK_U) {
            jButton7.doClick(); 
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_I) {
            jButton8.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_O) {
            jButton9.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_P) {
            jButton10.doClick();               
            }
        if (evt.getKeyCode() == KeyEvent.VK_OPEN_BRACKET) {
            jButton11.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_CLOSE_BRACKET) {
            jButton12.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_A) {
            jButton13.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_S) {
            jButton14.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_D) {
            jButton15.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_F) {
            jButton16.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_G) {
            jButton17.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_H) {
            jButton18.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_J) {
            jButton19.doClick();
                
            }
        if (evt.getKeyCode() == KeyEvent.VK_K) {
            jButton20.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_L) {
            jButton21.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_SEMICOLON) {
            jButton22.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_QUOTE) {
            jButton23.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_BACK_SLASH) {
            jButton24.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_Z) {
            jButton25.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_X) {
            jButton26.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_C) {
            jButton27.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_V) {
            jButton28.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_B) {
            jButton29.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_N) {
            jButton30.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_M) {
            jButton31.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_COMMA) {
            jButton32.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_PERIOD) {
            jButton33.doClick();
            }
        if (evt.getKeyCode() == KeyEvent.VK_SLASH) {
            jButton34.doClick();
            }
//        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
//            jButton35.doClick();
//            }
        
                
    }//GEN-LAST:event_formKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DropLoop3.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DropLoop4EMinSub.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\WhiteNoise Down.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\BigClap6.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\ClosedHihat3.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {
                    
                     String path = "Tune\\PianoLoop2.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    if (player.isActive()) {
                        player.stop();
                
                    }
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DropLoop4EMinLead.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChantWhat.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\StringLoop17Emin.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\StringLoop20Emin.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\Riser.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\VocalChop9.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\HouseKick3.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChant_Hey.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChantCome On.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChantOh.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChantYeah.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DryChantYee.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\Kick4E.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\TightClap.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\BigClap6.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\ClosedHihat3.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\OdysseyRide3.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "Tune\\DrumLoop4.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        // TODO add your handling code here:
        try {
                    
                    String path = "B_Drum.wav";
                    AudioInputStream audio = AudioSystem.getAudioInputStream(new File(path));
                    Clip player = AudioSystem.getClip();
                    player.open(audio);
                    player.start();
                    
                } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
                }
    }//GEN-LAST:event_jButton34ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());               
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
                
            }

            
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
